export {default as InitailScreen}  from './Initial/InitialScreen'
export {default as Login}  from './Login/Login'
export {default as Signup}  from './SignUp/SignUp'
export {default as Home}  from './Home/Home'
export {default as Search}  from './Search/Search'
export {default as Notification}  from './Notification/Notification'
export {default as Profile}  from './Profile/Profile'
export {default as Post}  from './Post/Post.tsx'
// export {default as HomeStack}  from './Home/HomeStack.tsx'
// export {default as ProfileStack}  from './Profile/ProfileStack.tsx'
// export {default as SearchStack}  from './Search/SearchStack.tsx'